// <auto-generated/>
#pragma warning disable CS0618
using IoT.KiotaClient.Api.Temperature.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace IoT.KiotaClient.Api.Temperature
{
    /// <summary>
    /// Builds and executes requests for operations under \api\temperature
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TemperatureRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the IoT.KiotaClient.api.temperature.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::IoT.KiotaClient.Api.Temperature.Item.TemperatureItemRequestBuilder"/></returns>
        public global::IoT.KiotaClient.Api.Temperature.Item.TemperatureItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::IoT.KiotaClient.Api.Temperature.Item.TemperatureItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the IoT.KiotaClient.api.temperature.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::IoT.KiotaClient.Api.Temperature.Item.TemperatureItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::IoT.KiotaClient.Api.Temperature.Item.TemperatureItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("id", position);
                return new global::IoT.KiotaClient.Api.Temperature.Item.TemperatureItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::IoT.KiotaClient.Api.Temperature.TemperatureRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TemperatureRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/temperature", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::IoT.KiotaClient.Api.Temperature.TemperatureRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TemperatureRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/temperature", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
